# This is a TOML document. Boom
Broker = "kafka"

[BrokerOption]
    topic = "goim-push-topic"
    addrs = ["127.0.0.1:9092"]
    AutoAck = true
    IsCunsumer = true
    Group = "goim-test"

[discovery]
    nodes = ["127.0.0.1:7171"]

[kafka]
    topic = "goim-push-topic"
    group = "goim-push-group-job"
    brokers = ["127.0.0.1:9092"]
